spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/loan
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    use-root-path: true

server:
  port: 10060
  forward-headers-strategy: framework

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Microservice URLs
application:
  config:
    account-url: http://localhost:8222/api/v1/accounts
    auth-url: http://localhost:8222/api/v1/auth
