spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

  mail:
    host: mail-dev
    port: 1025
    properties:
      mail:
        smtp:
          starttls:
            enable: false
          auth: false
springdoc:
  swagger-ui:
    use-root-path: true

server:
  port: 10090
  forward-headers-strategy: framework

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

application:
  config:
    account-url: http://localhost:8222/api/v1/accounts
    auth-url: http://localhost:8222/api/v1/auth
    kafka:
      transaction-topic: account-events
      retry-interval-ms: 1000